baseURL = "https://www.tooltoro.com/"
languageCode = "en-us"
title = "ToolToro — Simple AI tools, explained fast."
theme = "PaperMod"

[pagination]
  pagerSize = 10

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[outputs]
  home = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  env = "production"
  defaultTheme = "light"
  description = "Beginner-friendly AI and automation to save time and grow income."
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = false
  images = ["images/og-default.jpg"]

[params.homeInfoParams]
  Title = "Simple AI tools, explained fast."
  Content = "Beginner-friendly stacks, copy-paste prompts, and step-by-step guides to help you ship more in less time."

[menu]
  [[menu.main]]
    name = "Start Here"
    url = "/start/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 3

  [[menu.main]]
    name = "Prompts"
    url = "/prompts/"
    weight = 4

  [[menu.main]]
    name = "Disclosure"
    url = "/disclosure/"
    weight = 99
